server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: vid10
          uri: https://github.com/sandovalleonel/spring-boot-microservices
          search-paths: config-data
  application:
    name: config-service
